# nmap top 1000 TCP ports
# port, service, description
TOP_1000_PORTS = [
    [80, "http", "World Wide Web HTTP"],
    [23, "telnet", ""],
    [443, "https", "secure http (SSL)"],
    [21, "ftp", "File Transfer [Control]"],
    [22, "ssh", "Secure Shell Login"],
    [25, "smtp", "Simple Mail Transfer"],
    [
        3389,
        "ms-wbt-server",
        "Microsoft Remote Display Protocol (aka ms-term-serv, microsoft-rdp) | "
        "MS WBT Server",
    ],
    [110, "pop3", "PostOffice V.3 | Post Office Protocol - Version 3"],
    [445, "microsoft-ds", "SMB directly over IP"],
    [139, "netbios-ssn", "NETBIOS Session Service"],
    [143, "imap", "Interim Mail Access Protocol v2 | Internet Message Access Protocol"],
    [53, "domain", "Domain Name Server"],
    [135, "msrpc", "epmap | Microsoft RPC services | DCE endpoint resolution"],
    [3306, "mysql", ""],
    [
        8080,
        "http-proxy",
        "http-alt | Common HTTP proxy/second web server port | HTTP Alternate "
        "(see port 80)",
    ],
    [1723, "pptp", "Point-to-point tunnelling protocol"],
    [111, "rpcbind", "sunrpc | portmapper, rpcbind | SUN Remote Procedure Call"],
    [
        995,
        "pop3s",
        "POP3 protocol over TLS/SSL | pop3 protocol over TLS/SSL (was spop3) | "
        "POP3 over TLS protocol",
    ],
    [993, "imaps", "imap4 protocol over TLS/SSL | IMAP over TLS protocol"],
    [5900, "vnc", "rfb | Virtual Network Computer display 0 | Remote Framebuffer"],
    [
        1025,
        "NFS-or-IIS",
        "blackjack | IIS, NFS, or listener RFS remote_file_sharing | network blackjack",
    ],
    [587, "submission", "Message Submission"],
    [
        8888,
        "sun-answerbook",
        "ddi-udp-1 | ddi-tcp-1 | Sun Answerbook HTTP server. Or gnump3d "
        "streaming music server | NewsEDGE server TCP (TCP 1) | NewsEDGE "
        "server UDP (UDP 1)",
    ],
    [199, "smux", "SNMP Unix Multiplexer"],
    [
        1720,
        "h323q931",
        "h323hostcall | Interactive media | H.323 Call Control Signalling | "
        "H.323 Call Control",
    ],
    [
        465,
        "smtps",
        "submissions | igmpv3lite | urd | smtp protocol over TLS/SSL (was "
        "ssmtp) | URL Rendesvous Directory for SSM | IGMP over UDP for SSM | "
        "URL Rendezvous Directory for SSM | Message Submission over TLS "
        "protocol",
    ],
    [548, "afp", "afpovertcp | AFP over TCP"],
    [
        113,
        "ident",
        "auth | ident, tap, Authentication Service | Authentication Service",
    ],
    [81, "hosts2-ns", "HOSTS2 Name Server"],
    [6001, "X11:1", "X Window server"],
    [
        10000,
        "snet-sensor-mgmt",
        "ndmp | SecureNet Pro Sensor https management server or apple airport "
        "admin | Network Data Management Protocol",
    ],
    [
        514,
        "shell",
        "syslog | BSD rshd(8) | cmd like exec, but automatic authentication is "
        "performed as for login server",
    ],
    [5060, "sip", "Session Initiation Protocol (SIP)"],
    [179, "bgp", "Border Gateway Protocol"],
    [
        1026,
        "LSA-or-nterm",
        "cap | nterm remote_login network_terminal | Calendar Access Protocol",
    ],
    [
        2000,
        "cisco-sccp",
        "cisco SCCP (Skinny Client Control Protocol) | Cisco SCCP | Cisco SCCp",
    ],
    [8443, "https-alt", "pcsync-https | Common alternative https port | PCsync HTTPS"],
    [8000, "http-alt", "irdmi | A common alternative http port | iRDMI"],
    [32768, "filenet-tms", "Filenet TMS"],
    [
        554,
        "rtsp",
        "Real Time Stream Control Protocol | Real Time Streaming Protocol (RTSP)",
    ],
    [26, "rsftp", "RSFTP"],
    [1433, "ms-sql-s", "Microsoft-SQL-Server"],
    [49152, "unknown", ""],
    [2001, "dc", "wizard | or nfr20 web queries | curry"],
    [515, "printer", "spooler (lpd) | spooler"],
    [8008, "http", "http-alt | IBM HTTP server | HTTP Alternate"],
    [49154, "unknown", ""],
    [1027, "IIS", "6a44 | IPv6 Behind NAT44 CPEs"],
    [5666, "nrpe", "Nagios NRPE | Nagios Remote Plugin Executor"],
    [646, "ldp", "Label Distribution"],
    [5000, "upnp", "commplex-main | Universal PnP, also Free Internet Chess Server"],
    [5631, "pcanywheredata", ""],
    [
        631,
        "ipp",
        "ipps | Internet Printing Protocol -- for one implementation see "
        "http://www.cups.org (Common UNIX Printing System) | IPP (Internet "
        "Printing Protocol) | Internet Printing Protocol over HTTPS",
    ],
    [49153, "unknown", ""],
    [
        8081,
        "blackice-icecap",
        "sunproxyadmin | ICECap user console | Sun Proxy Admin Service",
    ],
    [2049, "nfs", "networked file system"],
    [88, "kerberos-sec", "kerberos | Kerberos (v5) | Kerberos"],
    [79, "finger", ""],
    [5800, "vnc-http", "Virtual Network Computer HTTP Access, display 0"],
    [106, "pop3pw", "3com-tsmux | Eudora compatible PW changer | 3COM-TSMUX"],
    [2121, "ccproxy-ftp", "scientia-ssdb | CCProxy FTP Proxy | SCIENTIA-SSDB"],
    [
        1110,
        "nfsd-status",
        "nfsd-keepalive | webadmstart | Cluster status info | Start web admin "
        "server | Client status info",
    ],
    [49155, "unknown", ""],
    [6000, "X11", "X Window server"],
    [
        513,
        "login",
        "who | BSD rlogind(8) | remote login a la telnet; automatic "
        "authentication performed based on priviledged port numbers and "
        'distributed data bases which identify "authentication domains" | '
        "maintains data bases showing who's logged in to machines on a local "
        "net and the load average of the machine",
    ],
    [990, "ftps", "ftp protocol, control, over TLS/SSL"],
    [5357, "wsdapi", "Web Services for Devices"],
    [427, "svrloc", "Server Location"],
    [49156, "unknown", ""],
    [543, "klogin", "Kerberos (v4/v5)"],
    [544, "kshell", "krcmd Kerberos (v4/v5) | krcmd"],
    [
        5101,
        "admdog",
        "talarian-udp | talarian-tcp | (chili!soft asp) | Talarian_TCP | Talarian_UDP",
    ],
    [144, "news", "uma | NewS window system | Universal Management Architecture"],
    [7, "echo", ""],
    [389, "ldap", "Lightweight Directory Access Protocol"],
    [
        8009,
        "ajp13",
        "nvme-disc | Apache JServ Protocol 1.3 | NVMe over Fabrics Discovery Service",
    ],
    [3128, "squid-http", "ndl-aas | Active API Server Port"],
    [444, "snpp", "Simple Network Paging Protocol"],
    [9999, "abyss", "Abyss web server remote web management interface | distinct"],
    [
        5009,
        "airport-admin",
        "winfs | Apple AirPort WAP Administration | Microsoft Windows Filesystem",
    ],
    [7070, "realserver", "arcp | ARCP"],
    [5190, "aol", "America-Online. Also can be used by ICQ | America-Online"],
    [
        3000,
        "ppp",
        "remoteware-cl | hbci | User-level ppp daemon, or chili!soft asp | "
        "HBCI | RemoteWare Client",
    ],
    [5432, "postgresql", "PostgreSQL database server | PostgreSQL Database"],
    [1900, "upnp", "ssdp | Universal PnP | SSDP"],
    [3986, "mapper-ws_ethd", "mapper-ws-ethd | MAPPER workstation server"],
    [13, "daytime", ""],
    [1029, "ms-lsa", "solid-mux | Solid Mux Server"],
    [9, "discard", "sink null"],
    [5051, "ida-agent", "ita-agent | Symantec Intruder Alert | ITA Agent"],
    [6646, "unknown", ""],
    [49157, "unknown", ""],
    [1028, "unknown", ""],
    [873, "rsync", "Rsync server ( http://rsync.samba.org )"],
    [1755, "wms", "Windows media service | ms-streaming"],
    [2717, "pn-requester", "PN REQUESTER"],
    [
        4899,
        "radmin",
        "radmin-port | Radmin (www.radmin.com) remote PC control software | "
        "RAdmin Port",
    ],
    [
        9100,
        "jetdirect",
        "pdl-datastream | hp-pdl-datastr | HP JetDirect card | PDL Data "
        "Streaming Port | Printer PDL Data Stream",
    ],
    [119, "nntp", "Network News Transfer Protocol"],
    [37, "time", "timserver"],
    [1000, "cadlock", "cadlock2"],
    [
        3001,
        "nessus",
        "origo-native | Nessus Security Scanner (www.nessus.org) Daemon or "
        "chili!soft asp | OrigoDB Server Native Interface",
    ],
    [5001, "commplex-link", ""],
    [82, "xfer", "XFER Utility"],
    [10010, "rxapi", "ooRexx rxapi services"],
    [1030, "iad1", "BBN IAD"],
    [9090, "zeus-admin", "websm | Zeus admin server | WebSM"],
    [
        2107,
        "msmq-mgmt",
        "bintec-admin | Microsoft Message Queuing (IANA calls this "
        "bintec-admin) | BinTec Admin",
    ],
    [1024, "kdm", "K Display Manager (KDE version of xdm)"],
    [2103, "zephyr-clt", "Zephyr serv-hm connection"],
    [6004, "X11:4", "X Window server"],
    [1801, "msmq", "Microsoft Message Queuing | Microsoft Message Que"],
    [5050, "mmcc", "multimedia conference control tool"],
    [19, "chargen", "ttytst source Character Generator | Character Generator"],
    [8031, "unknown", ""],
    [1041, "danf-ak2", "AK2 Product"],
    [255, "unknown", ""],
    [2967, "symantec-av", "ssc-agent | Symantec AntiVirus (rtvscan.exe) | SSC-AGENT"],
    [1049, "td-postman", "Tobit David Postman VPMN"],
    [1048, "neod2", "Sun's NEO Object Request Broker"],
    [1053, "remote-as", "Remote Assistant (RA)"],
    [3703, "adobeserver-3", "Adobe Server 3"],
    [1056, "vfo", ""],
    [1065, "syscomlan", ""],
    [1064, "jstel", ""],
    [1054, "brvread", ""],
    [17, "qotd", "Quote of the Day"],
    [808, "ccproxy-http", "CCProxy HTTP/Gopher/FTP (over HTTP) proxy"],
    [
        3689,
        "rendezvous",
        "daap | Rendezvous Zeroconf (used by Apple/iTunes) | Digital Audio "
        "Access Protocol (iTunes)",
    ],
    [1031, "iad2", "BBN IAD"],
    [1044, "dcutility", "Dev Consortium Utility"],
    [1071, "bsquare-voip", ""],
    [5901, "vnc-1", "Virtual Network Computer display 1"],
    [
        9102,
        "jetdirect",
        "bacula-fd | HP JetDirect card. Also used (and officially registered "
        "for) Bacula File Daemon (an open source backup system) | Bacula File "
        "Daemon",
    ],
    [100, "newacct", "[unauthorized use]"],
    [8010, "xmpp", "XMPP File Transfer"],
    [2869, "icslap", "Universal Plug and Play Device Host, SSDP Discovery Service"],
    [1039, "sbl", "Streamlined Blackhole"],
    [5120, "barracuda-bbs", "Barracuda Backup Protocol"],
    [4001, "newoak", ""],
    [9000, "cslistener", ""],
    [2105, "eklogin", "minipay | Kerberos (v4) encrypted rlogin | MiniPay"],
    [636, "ldapssl", "ldaps | LDAP over SSL | ldap protocol over TLS/SSL (was sldap)"],
    [1038, "mtqp", "Message Tracking Query Protocol"],
    [2601, "zebra", "discp-client | zebra vty | discp client"],
    [7000, "afs3-fileserver", "file server itself, msdos | file server itself"],
    [
        1,
        "tcpmux",
        "TCP Port Service Multiplexer [rfc-1078] | TCP Port Service Multiplexer",
    ],
    [1066, "fpo-fns", ""],
    [1069, "cognex-insight", ""],
    [625, "apple-xsrvr-admin", "dec_dlm | dec-dlm | Apple Mac Xserver admin | DEC DLM"],
    [311, "asip-webadmin", "appleshare ip webadmin | AppleShare IP WebAdmin"],
    [280, "http-mgmt", ""],
    [254, "unknown", ""],
    [
        4000,
        "remoteanything",
        "terabase | neoworx remote-anything slave remote control | Terabase",
    ],
    [
        5003,
        "filemaker",
        "fmpro-internal | Filemaker Server - "
        "http://www.filemaker.com/ti/104289.html | FileMaker, Inc. - "
        "Proprietary transport | FileMaker, Inc. - Proprietary name binding",
    ],
    [1761, "landesk-rc", "LANDesk Remote Control | cft-0"],
    [2002, "globe", ""],
    [2005, "deslogin", "oracle | berknet | encrypted symmetric telnet/login"],
    [1998, "x25-svc-port", "cisco X.25 service (XOT)"],
    [1032, "iad3", "BBN IAD"],
    [
        1050,
        "java-or-OTGfileshare",
        "cma | J2EE nameserver, also OTG, also called Disk/Application "
        "extender. Could also be MiniCommand backdoor OTGlicenseserv | CORBA "
        "Management Agent",
    ],
    [
        6112,
        "dtspc",
        "dtspcd | CDE subprocess control | Desk-Top Sub-Process Control Daemon",
    ],
    [3690, "svn", "Subversion"],
    [1521, "oracle", "ncube-lm | Oracle Database | nCube License Manager"],
    [2161, "apc-agent", "apc-2161 | American Power Conversion | APC 2161"],
    [6002, "X11:2", "X Window server"],
    [1080, "socks", ""],
    [2401, "cvspserver", "CVS network server"],
    [4045, "lockd", "npp | Network Paging Protocol"],
    [
        902,
        "iss-realsecure",
        "ideafarm-door | ISS RealSecure Sensor | self documenting Telnet Door "
        "| self documenting Door: send 0x00 for info",
    ],
    [7937, "nsrexecd", "Legato NetWorker"],
    [787, "qsc", ""],
    [1058, "nim", ""],
    [2383, "ms-olap4", "MS OLAP 4 | Microsoft OLAP"],
    [
        32771,
        "sometimes-rpc5",
        "filenet-rmi | Sometimes an RPC port on my Solaris box (rusersd) | "
        "FileNET RMI | FileNet RMI",
    ],
    [
        1033,
        "netinfo",
        "netinfo-local | Netinfo is apparently on many OS X boxes. | local "
        "netinfo port",
    ],
    [1040, "netsaint", "netarx | Netsaint status daemon | Netarx Netcare"],
    [1059, "nimreg", ""],
    [50000, "ibm-db2", "(also Internet/Intranet Input Method Server Framework?)"],
    [5555, "freeciv", "personal-agent | Personal Agent"],
    [10001, "scp-config", "SCP Configuration"],
    [1494, "citrix-ica", "ica"],
    [
        2301,
        "compaqdiag",
        "cpq-wbem | Compaq remote diagnostic/management | Compaq HTTP",
    ],
    [593, "http-rpc-epmap", "HTTP RPC Ep Map"],
    [3, "compressnet", "Compression Process"],
    [3268, "globalcatLDAP", "msft-gc | Global Catalog LDAP | Microsoft Global Catalog"],
    [7938, "lgtomapper", "Legato portmapper"],
    [1234, "hotline", "search-agent | Infoseek Search Agent"],
    [
        1022,
        "exp2",
        "RFC3692-style Experiment 2 (*) [RFC4727] | RFC3692-style Experiment 2",
    ],
    [
        1035,
        "multidropper",
        "mxxrlogin | A Multidropper Adware, or PhoneFree | MX-XR RPC",
    ],
    [9001, "tor-orport", "etlservicemgr | Tor ORPort | ETL Service Manager"],
    [1074, "warmspotMgmt", "Warmspot Management Protocol"],
    [8002, "teradataordbms", "Teradata ORDBMS"],
    [1036, "nsstp", "Nebula Secure Segment Transfer Protocol"],
    [1037, "ams", ""],
    [464, "kpasswd5", "Kerberos (v5) | kpasswd"],
    [
        1935,
        "rtmp",
        "macromedia-fcs | Macromedia FlasComm Server | Macromedia Flash "
        "Communications Server MX | Macromedia Flash Communications server MX",
    ],
    [6666, "irc", "internet relay chat server"],
    [2003, "finger", "brutus | GNU finger (cfingerd) | Brutus Server"],
    [497, "retrospect", "Retrospect backup and restore service"],
    [6543, "mythtv", "lds-distrib | lds_distrib"],
    [1352, "lotusnotes", "lotusnote | Lotus Note"],
    [24, "priv-mail", "any private mail system"],
    [
        3269,
        "globalcatLDAPssl",
        "msft-gc-ssl | Global Catalog LDAP over ssl | Microsoft Global Catalog "
        "with LDAP/SSL",
    ],
    [1111, "lmsocialserver", "LM Social Server"],
    [407, "timbuktu", ""],
    [500, "isakmp", ""],
    [20, "ftp-data", "File Transfer [Default Data]"],
    [2006, "invokator", "raid-cd | raid"],
    [3260, "iscsi", "iscsi-target | iSCSI port"],
    [1034, "zincite-a", "activesync | Zincite.A backdoor | ActiveSync Notifications"],
    [
        15000,
        "hydap",
        "Hypack Hydrographic Software Packages Data Acquisition | Hypack Data "
        "Aquisition",
    ],
    [1218, "aeroflight-ads", "AeroFlight ADs"],
    [4444, "krb524", "nv-video | Kerberos 5 to 4 ticket xlator | NV Video default"],
    [264, "bgmp", ""],
    [2004, "mailbox", "emce | CCWS mm conf"],
    [33, "dsp", "Display Support Protocol"],
    [1042, "afrog", "Subnet Roaming"],
    [42510, "caerpc", "CA eTrust RPC"],
    [999, "garcon", "puprouter | applix | Applix ac"],
    [3052, "powerchute", "apc-3052 | APC 3052"],
    [1023, "netvenuechat", "Nortel NetVenue Notification, Chat, Intercom"],
    [1068, "instl_bootc", "instl-bootc | Installation Bootstrap Proto. Cli."],
    [222, "rsh-spx", "Berkeley rshd with SPX auth"],
    [888, "accessbuilder", "cddbp | or Audio CD Database | CD Database Protocol"],
    [7100, "font-service", "X Font Service"],
    [563, "snews", "nntps | nntp protocol over TLS/SSL (was snntp)"],
    [1717, "fj-hdnet", ""],
    [2008, "conf", "terminaldb"],
    [992, "telnets", "telnet protocol over TLS/SSL"],
    [
        32770,
        "sometimes-rpc3",
        "filenet-nch | Sometimes an RPC port on my Solaris box | Filenet NCH",
    ],
    [
        32772,
        "sometimes-rpc7",
        "filenet-pa | Sometimes an RPC port on my Solaris box (status) | "
        "FileNET Process Analyzer",
    ],
    [7001, "afs3-callback", "callbacks to cache managers"],
    [
        8082,
        "blackice-alerts",
        "us-cli | BlackIce Alerts sent to this port | Utilistor (Client)",
    ],
    [2007, "dectalk", "raid-am"],
    [
        5550,
        "sdadmind",
        "cbus | ACE/Server services | Model Railway control using the CBUS "
        "message protocol",
    ],
    [2009, "news", "whosockami"],
    [
        1043,
        "boinc",
        "boinc-client | BOINC Client Control or Microsoft IIS | BOINC Client Control",
    ],
    [
        512,
        "exec",
        "biff | comsat | BSD rexecd(8) | remote process execution; "
        "authentication performed using passwords and UNIX login names | used "
        "by mail system to notify users of new mail received; currently "
        "receives messages only from processes on the same machine",
    ],
    [5801, "vnc-http-1", "Virtual Network Computer HTTP Access, display 1"],
    [
        7019,
        "doceri-ctl",
        "doceri-view | doceri drawing service control | doceri drawing service "
        "screen view",
    ],
    [2701, "sms-rcinfo", "SMS RCINFO"],
    [50001, "unknown", ""],
    [1700, "mps-raft", ""],
    [4662, "edonkey", "oms | eDonkey file sharing (Donkey) | OrbitNet Message Service"],
    [2065, "dlsrpn", "Data Link Switch Read Port Number"],
    [2010, "search", "pipe_server | pipe-server | Or nfr411"],
    [42, "nameserver", "name | Host Name Server"],
    [9535, "man", "mngsuite | Management Suite Remote Control"],
    [2602, "ripd", "discp-server | RIPd vty | discp server"],
    [3333, "dec-notes", "DEC Notes"],
    [161, "snmp", ""],
    [
        5100,
        "admd",
        "socalia | (chili!soft asp admin port) or Yahoo pager | Socalia service mux",
    ],
    [2604, "ospfd", "nsc-ccs | OSPFd vty | NSC CCS"],
    [4002, "mlchat-proxy", "mlnet - MLChat P2P chat proxy | pxc-spvr-ft"],
    [5002, "rfe", "Radio Free Ethernet | radio free ethernet"],
    [
        8192,
        "sophos",
        "spytechphone | Sophos Remote Management System | SpyTech Phone Service",
    ],
    [
        6789,
        "ibm-db2-admin",
        "radg | smc-https | IBM DB2 | SMC-HTTPS | GSS-API for the Oracle "
        "Remote Administration Daemon",
    ],
    [8194, "sophos", "blp1 | Sophos Remote Management System | Bloomberg data API"],
    [6059, "X11:59", "X Window server"],
    [1047, "neod1", "Sun's NEO Object Request Broker"],
    [8193, "sophos", "Sophos Remote Management System"],
    [2702, "sms-xfer", "SMS XFER"],
    [9595, "pds", "Ping Discovery System | Ping Discovery Service"],
    [1051, "optima-vnet", "Optima VNET"],
    [9594, "msgsys", "Message System"],
    [9593, "cba8", "LANDesk Management Agent (cba8)"],
    [16993, "amt-soap-https", "Intel(R) AMT SOAP/HTTPS"],
    [16992, "amt-soap-http", "Intel(R) AMT SOAP/HTTP"],
    [5226, "hp-status", "HP Status"],
    [5225, "hp-server", "HP Server"],
    [32769, "filenet-rpc", "Filenet RPC"],
    [1052, "ddt", "Dynamic DNS tools | Dynamic DNS Tools"],
    [1055, "ansyslmd", "ANSYS - License Manager"],
    [
        3283,
        "netassistant",
        "#ERROR:Apple Remote Desktop (Net Assistant) | Apple Remote Desktop "
        "Net Assistant reporting feature | Net Assistant",
    ],
    [1062, "veracity", ""],
    [9415, "unknown", ""],
    [8701, "unknown", ""],
    [8652, "unknown", ""],
    [8651, "unknown", ""],
    [8089, "unknown", ""],
    [65389, "unknown", ""],
    [65000, "unknown", ""],
    [64680, "unknown", ""],
    [64623, "unknown", ""],
    [55600, "unknown", ""],
    [55555, "unknown", ""],
    [52869, "unknown", ""],
    [35500, "unknown", ""],
    [33354, "unknown", ""],
    [23502, "unknown", ""],
    [20828, "unknown", ""],
    [1311, "rxmon", ""],
    [1060, "polestar", ""],
    [4443, "pharos", ""],
    [730, "netviewdm2", "IBM NetView DM/6000 send/tcp"],
    [731, "netviewdm3", "IBM NetView DM/6000 receive/tcp"],
    [709, "entrustmanager", "EntrustManager - NorTel DES auth network see 389/tcp"],
    [1067, "instl_boots", "instl-boots | Installation Bootstrap Proto. Serv."],
    [13782, "netbackup", "bpcd | bpcd client | VERITAS NetBackup"],
    [5902, "vnc-2", "Virtual Network Computer display 2"],
    [366, "odmr", ""],
    [
        9050,
        "tor-socks",
        "versiera | Tor SocksPort, www.torproject.org | Versiera Agent Listener",
    ],
    [
        1002,
        "windows-icfw",
        "Windows Internet Connection Firewall or Internet Locator Server for "
        "NetMeeting.",
    ],
    [85, "mit-ml-dev", "MIT ML Device"],
    [5500, "hotline", "Hotline file sharing client/server | fcp-addr-srvr1"],
    [1864, "paradym-31", "paradym-31port | Paradym 31 Port"],
    [5431, "park-agent", "PARK AGENT"],
    [1863, "msnp", "MSN Messenger"],
    [8085, "unknown", ""],
    [51103, "unknown", ""],
    [49999, "unknown", ""],
    [45100, "unknown", ""],
    [10243, "unknown", ""],
    [49, "tacacs", "Login Host Protocol (TACACS)"],
    [6667, "irc", "Internet Relay Chat"],
    [90, "dnsix", "DNSIX Securit Attribute Token Map"],
    [27000, "flexlm0", "FlexLM license manager additional ports"],
    [1503, "imtc-mcs", "Databeam"],
    [6881, "bittorrent-tracker", "BitTorrent tracker"],
    [
        8021,
        "ftp-proxy",
        "intu-ec-client | Common FTP proxy port | Intuit Entitlement Client",
    ],
    [1500, "vlsi-lm", "VLSI License Manager"],
    [340, "unknown", ""],
    [5566, "westec-connect", "Westec Connect"],
    [8088, "radan-http", "Radan HTTP"],
    [2222, "EtherNetIP-1", "EtherNet/IP-1 | EtherNet-IP-1 | EtherNet/IP I/O"],
    [9071, "unknown", ""],
    [8899, "ospf-lite", ""],
    [1501, "sas-3", "saiscm | Satellite-data Acquisition System 3"],
    [5102, "admeng", "oms-nonsecure | (chili!soft asp) | Oracle OMS non-secure"],
    [
        32774,
        "sometimes-rpc11",
        "filenet-re | Sometimes an RPC port on my Solaris box (rusersd) | "
        "FileNET Rules Engine",
    ],
    [
        32773,
        "sometimes-rpc9",
        "filenet-cm | Sometimes an RPC port on my Solaris box (rquotad) | "
        "FileNET Component Manager",
    ],
    [9101, "jetdirect", "bacula-dir | HP JetDirect card | Bacula Director"],
    [6005, "X11:5", "X Window server"],
    [9876, "sd", "Session Director"],
    [
        5679,
        "activesync",
        "dccm | Microsoft ActiveSync PDY synchronization | Direct Cable "
        "Connect Manager",
    ],
    [163, "cmip-man", "CMIP/TCP Manager"],
    [648, "rrp", "Registry Registrar Protocol (RRP)"],
    [146, "iso-tp0", "ISO-IP0"],
    [1666, "netview-aix-6", ""],
    [
        901,
        "samba-swat",
        "smpnameres | Samba SWAT tool. Also used by ISS RealSecure. | SMPNAMERES",
    ],
    [83, "mit-ml-dev", "MIT ML Device"],
    [9207, "wap-vcal-s", "WAP vCal Secure"],
    [8001, "vcom-tunnel", "VCOM Tunnel"],
    [8083, "us-srv", "Utilistor (Server)"],
    [5004, "avt-profile-1", "RTP media data [RFC 3551][RFC 4571] | RTP media data"],
    [3476, "nppmp", "NVIDIA Mgmt Protocol"],
    [8084, "unknown", ""],
    [5214, "unknown", ""],
    [14238, "unknown", ""],
    [
        12345,
        "netbus",
        "italk | NetBus backdoor trojan or Trend Micro Office Scan | Italk Chat System",
    ],
    [912, "apex-mesh", "APEX relay-relay service"],
    [30, "unknown", ""],
    [2605, "bgpd", "nsc-posa | BGPd vty | NSC POSA"],
    [2030, "device2", ""],
    [6, "unknown", ""],
    [541, "uucp-rlogin", ""],
    [
        8007,
        "ajp12",
        "warppipe | Apache JServ Protocol 1.x | I/O oriented cluster computing "
        "software",
    ],
    [
        3005,
        "deslogin",
        "geniuslm | encrypted symmetric telnet/login | Genius License Manager",
    ],
    [4, "unknown", ""],
    [1248, "hermes", ""],
    [2500, "rtsserv", "Resource Tracking system server"],
    [880, "unknown", ""],
    [306, "unknown", ""],
    [
        4242,
        "vrml-multi-use",
        "VRML Multi User Systems or CrashPlan "
        "http://support.code42.com/CrashPlan/Latest/Configuring/Network#Networking_FAQs",
    ],
    [1097, "sunclustermgr", "Sun Cluster Manager"],
    [9009, "pichat", "Pichat Server"],
    [2525, "ms-v-worlds", "MS V-Worlds"],
    [1086, "cplscrambler-lg", "CPL Scrambler Logging"],
    [1088, "cplscrambler-al", "CPL Scrambler Alarm Log"],
    [8291, "unknown", ""],
    [52822, "unknown", ""],
    [
        6101,
        "backupexec",
        "synchronet-rtc | Backup Exec UNIX and 95/98/ME Aent | SynchroNet-rtc",
    ],
    [900, "omginitialrefs", "OMG Initial Refs"],
    [7200, "fodms", "FODMS FLIP"],
    [2809, "corbaloc", "Corba | CORBA LOC"],
    [800, "mdbs_daemon", "mdbs-daemon"],
    [
        32775,
        "sometimes-rpc13",
        "filenet-pch | Sometimes an RPC port on my Solaris box (status) | "
        "Performance Clearinghouse",
    ],
    [
        12000,
        "cce4x",
        "entextxid | ClearCommerce Engine 4.x (www.clearcommerce.com) | IBM "
        "Enterprise Extender SNA XID Exchange",
    ],
    [1083, "ansoft-lm-1", "Anasoft License Manager"],
    [211, "914c-g", "914c/g | Texas Instruments 914C/G Terminal"],
    [987, "unknown", ""],
    [705, "agentx", ""],
    [
        20005,
        "btx",
        "openwebnet | xcept4 (Interacts with German Telekom's CEPT videotext "
        "service) | OpenWebNet protocol for electric network",
    ],
    [711, "cisco-tdp", "Cisco TDP"],
    [13783, "netbackup", "vopied | vopied client | VOPIED Protocol"],
    [6969, "acmsoda", ""],
    [
        3071,
        "csd-mgmt-port",
        "xplat-replicate | ContinuStor Manager Port | Crossplatform "
        "replication protocol",
    ],
    [3801, "ibm-mgr", "ibm manager service"],
    [3017, "event_listener", "event-listener | Event Listener"],
    [8873, "dxspider", "dxspider linking protocol"],
    [5269, "xmpp-server", "XMPP Server Connection"],
    [5222, "xmpp-client", "XMPP Client Connection"],
    [1046, "wfremotertm", "WebFilter Remote Monitor"],
    [1085, "webobjects", "Web Objects"],
    [5987, "wbem-rmi", "WBEM RMI"],
    [5989, "wbem-https", "WBEM CIM-XML (HTTPS)"],
    [5988, "wbem-http", "WBEM CIM-XML (HTTP)"],
    [2190, "tivoconnect", "TiVoConnect Beacon"],
    [11967, "sysinfo-sp", "SysInfo Service Protocol | SysInfo Sercice Protocol"],
    [8600, "asterix", "Surveillance Data"],
    [8087, "simplifymedia", "Simplify Media SPP Protocol"],
    [30000, "ndmps", "Secure Network Data Management Protocol"],
    [9010, "sdr", "Secure Data Replicator Protocol"],
    [7741, "scriptview", "ScriptView Network"],
    [3367, "satvid-datalnk", "Satellite Video Data Link"],
    [3766, "sitewatch-s", "SSL e-watch sitewatch server"],
    [7627, "soap-http", "SOAP Service Port"],
    [14000, "scotty-ft", "SCOTTY High-Speed Filetransfer"],
    [3031, "eppc", "Remote AppleEvents/PPC Toolbox"],
    [1099, "rmiregistry", "RMI Registry"],
    [1098, "rmiactivation", "RMI Activation"],
    [6580, "parsec-master", "Parsec Masterserver"],
    [2718, "pn-requester2", "PN REQUESTER 2"],
    [15002, "onep-tls", "Open Network Environment TLS"],
    [4129, "nuauth", "NuFW authentication protocol"],
    [6901, "jetstream", "Novell Jetstream messaging protocol"],
    [3827, "netmpi", "Netadmin Systems MPI service"],
    [3580, "nati-svrloc", "NATI-ServiceLocator"],
    [2144, "lv-ffx", "Live Vault Fast Object Transfer"],
    [8181, "intermapper", "Intermapper network management system"],
    [9900, "iua", "IUA"],
    [1718, "h323gatedisc", "H.323 Multicast Gatekeeper Discover"],
    [9080, "glrpc", "Groove GLRPC"],
    [2135, "gris", "Grid Resource Information Server"],
    [2811, "gsiftp", "GSI FTP"],
    [1045, "fpitp", "Fingerprint Image Transfer Protocol"],
    [2399, "fmpro-fdal", "FileMaker, Inc. - Data Access Layer"],
    [1148, "elfiq-repl", "Elfiq Replication Service"],
    [10002, "documentum", "EMC-Documentum Content Server Product"],
    [9002, "dynamid", "DynamID authentication"],
    [8086, "d-s-n", "Distributed SCADA Networking Rendezvous Port"],
    [3998, "dnx", "Distributed Nagios Executor Service"],
    [2607, "connection", "Dell Connection"],
    [
        11110,
        "sgi-soap",
        "Data migration facility (DMF) SOAP is a web server protocol to "
        "support remote access to DMF",
    ],
    [4126, "ddrepl", "Data Domain Replication Service"],
    [2875, "dxmessagebase2", "DX Message Base Transport Protocol"],
    [5718, "dpm", "DPM Communication Server"],
    [9011, "d-star", "D-Star Routing digital voice+data for amateur radio"],
    [5911, "cpdlc", "Controller Pilot Data Link Communication"],
    [5910, "cm", "Context Management"],
    [9618, "condor", "Condor Collector Service"],
    [2381, "compaq-https", "Compaq HTTPS"],
    [1096, "cnrprotocol", "Common Name Resolution Protocol"],
    [3300, "ceph", "Ceph monitor"],
    [3351, "btrieve", "Btrieve port"],
    [1073, "bridgecontrol", "Bridge Control"],
    [
        8333,
        "bitcoin",
        "Bitcoin crypto currency - https://en.bitcoin.it/wiki/Running_Bitcoin",
    ],
    [15660, "bex-xr", "Backup Express Restore Server"],
    [6123, "backup-express", "Backup Express"],
    [3784, "bfd-control", "BFD Control Protocol"],
    [5633, "beorl", "BE Operations Request Listener"],
    [3211, "avsecuremgmt", "Avocent Secure Management"],
    [1078, "avocent-proxy", "Avocent Proxy Protocol"],
    [3659, "apple-sasl", "Apple SASL"],
    [3551, "apcupsd", "Apcupsd Information Port"],
    [2100, "amiganetfs", "Amiga Network Filesystem"],
    [16001, "fmsascon", "Administration Server Connector"],
    [3325, "active-net", "Active Networks"],
    [3323, "active-net", "Active Networks"],
    [2260, "apc-2260", "APC 2260"],
    [2160, "apc-2160", "APC 2160"],
    [1104, "xrl", ""],
    [9968, "unknown", ""],
    [9503, "unknown", ""],
    [9502, "unknown", ""],
    [9485, "unknown", ""],
    [9290, "unknown", ""],
    [9220, "unknown", ""],
    [8994, "unknown", ""],
    [8649, "unknown", ""],
    [8222, "unknown", ""],
    [7911, "unknown", ""],
    [7625, "unknown", ""],
    [7106, "unknown", ""],
    [65129, "unknown", ""],
    [63331, "unknown", ""],
    [6156, "unknown", ""],
    [6129, "unknown", ""],
    [60020, "unknown", ""],
    [5962, "unknown", ""],
    [5961, "unknown", ""],
    [5960, "unknown", ""],
    [5959, "unknown", ""],
    [5925, "unknown", ""],
    [5877, "unknown", ""],
    [5825, "unknown", ""],
    [5810, "unknown", ""],
    [58080, "unknown", ""],
    [57294, "unknown", ""],
    [50800, "unknown", ""],
    [50006, "unknown", ""],
    [50003, "unknown", ""],
    [49160, "unknown", ""],
    [49159, "unknown", ""],
    [49158, "unknown", ""],
    [48080, "unknown", ""],
    [40193, "unknown", ""],
    [34573, "unknown", ""],
    [34572, "unknown", ""],
    [34571, "unknown", ""],
    [3404, "unknown", ""],
    [33899, "unknown", ""],
    [3301, "unknown", ""],
    [32782, "unknown", ""],
    [32781, "unknown", ""],
    [31038, "unknown", ""],
    [30718, "unknown", ""],
    [28201, "unknown", ""],
    [27715, "unknown", ""],
    [25734, "unknown", ""],
    [24800, "unknown", ""],
    [22939, "unknown", ""],
    [21571, "unknown", ""],
    [20221, "unknown", ""],
    [20031, "unknown", ""],
    [19842, "unknown", ""],
    [19801, "unknown", ""],
    [19101, "unknown", ""],
    [17988, "unknown", ""],
    [1783, "unknown", ""],
    [16018, "unknown", ""],
    [16016, "unknown", ""],
    [15003, "unknown", ""],
    [14442, "unknown", ""],
    [13456, "unknown", ""],
    [10629, "unknown", ""],
    [10628, "unknown", ""],
    [10626, "unknown", ""],
    [10621, "unknown", ""],
    [10617, "unknown", ""],
    [10616, "unknown", ""],
    [10566, "unknown", ""],
    [10025, "unknown", ""],
    [10024, "unknown", ""],
    [10012, "unknown", ""],
    [1169, "tripwire", ""],
    [5030, "surfpass", ""],
    [5414, "statusd", ""],
    [1057, "startron", ""],
    [6788, "smc-http", ""],
    [1947, "sentinelsrm", ""],
    [1094, "rootd", ""],
    [1075, "rdrmshc", ""],
    [1108, "ratio-adp", ""],
    [4003, "pxc-splr-ft", ""],
    [1081, "pvuniwien", ""],
    [1093, "proofd", ""],
    [4449, "privatewire", ""],
    [1687, "nsjtp-ctrl", ""],
    [1840, "netopia-vo2", ""],
    [1100, "mctp", ""],
    [1063, "kyoceranetdev", ""],
    [1061, "kiosk", ""],
    [1107, "isoipsigport-2", ""],
    [1106, "isoipsigport-1", ""],
    [9500, "ismserver", ""],
    [20222, "ipulse-ics", ""],
    [7778, "interwise", ""],
    [1077, "imgames", ""],
    [1310, "husky", ""],
    [2119, "gsigatekeeper", ""],
    [2492, "groove", ""],
    [1070, "gmrupdateserv", ""],
    [20000, "dnp", ""],
    [8400, "cvd", ""],
    [1272, "cspmlockmgr", ""],
    [6389, "clariion-evr01", ""],
    [7777, "cbt", ""],
    [1072, "cardax", ""],
    [1079, "asprovatalk", ""],
    [1082, "amt-esd-prot", ""],
    [8402, "abarsd", ""],
    [
        691,
        "resvc",
        "msexch-routing | The Microsoft Exchange 2000 Server Routing Service | "
        "MS Exchange Routing",
    ],
    [89, "su-mit-tg", "SU/MIT Telnet Gateway"],
    [
        32776,
        "sometimes-rpc15",
        "filenet-peior | Sometimes an RPC port on my Solaris box (sprayd) | "
        "FileNET BPM IOR",
    ],
    [1999, "tcp-id-port", "cisco identification port"],
    [1001, "webpush", "HTTP Web Push"],
    [212, "anet", "ATEXSSTR"],
    [2020, "xinupageserver", ""],
    [7002, "afs3-prserver", "users & groups database"],
    [
        2998,
        "iss-realsec",
        "realsecure | ISS RealSecure IDS Remote Console Admin port | Real Secure",
    ],
    [6003, "X11:3", "X Window server"],
    [50002, "iiimsf", "Internet/Intranet Input Method Server Framework"],
    [3372, "msdtc", "tip2 | MS distributed transaction coordinator | TIP 2"],
    [
        898,
        "sun-manageconsole",
        "Solaris Management Console Java listener (Solaris 8 & 9)",
    ],
    [5510, "secureidprop", "ACE/Server services"],
    [32, "unknown", ""],
    [2033, "glogger", ""],
    [5903, "vnc-3", "Virtual Network Computer display 3"],
    [99, "metagram", "Metagram Relay"],
    [749, "kerberos-adm", "Kerberos 5 admin/changepw | kerberos administration"],
    [425, "icad-el", "ICAD"],
    [43, "whois", "nicname | Who Is"],
    [5405, "pcduo", "netsupport | RemCon PC-Duo - new port | NetSupport"],
    [6106, "isdninfo", "mpsserver | i4lmond | MPS Server"],
    [13722, "netbackup", "bpjava-msvc | bpjava-msvc client | BP Java MSVC Protocol"],
    [
        6502,
        "netop-rc",
        "boks_servm | boks-servm | NetOp Remote Control (by Danware Data A/S) "
        "| BoKS Servm",
    ],
    [7007, "afs3-bos", "basic overseer process"],
    [458, "appleqtc", "apple quick time"],
    [1580, "tn-tl-r1", "tn-tl-r2"],
    [9666, "zoomcp", "Zoom Control Panel Game Server Management"],
    [8100, "xprint-server", "Xprint Server"],
    [3737, "xpanel", "XPanel Daemon"],
    [5298, "presence", "XMPP Link-Local Messaging"],
    [1152, "winpoplanmess", "Winpopup LAN Messenger"],
    [8090, "opsmessaging", "Vehicle to station messaging"],
    [2191, "tvbus", "TvBus Messaging"],
    [3011, "trusted-web", "Trusted Web"],
    [5200, "targus-getdata", "TARGUS GetData"],
    [3851, "spectraport", "SpectraTalk Port"],
    [3371, "satvid-datalnk", "Satellite Video Data Link"],
    [3370, "satvid-datalnk", "Satellite Video Data Link"],
    [3369, "satvid-datalnk", "Satellite Video Data Link"],
    [7402, "rtps-dd-mt", "RTPS Data-Distribution Meta-Traffic"],
    [5054, "rlm-admin", "RLM administrative interface"],
    [3918, "pktcablemmcops", "PacketCableMultimediaCOPS"],
    [3077, "orbix-loc-ssl", "Orbix 2000 Locator SSL"],
    [7443, "oracleas-https", "Oracle Application Server HTTPS"],
    [3493, "nut", "Network UPS Tools"],
    [3828, "neteh", "Netadmin Systems Event Handler"],
    [1186, "mysql-cluster", "MySQL Cluster Manager"],
    [2179, "vmrdp", "Microsoft RDP for virtual machines"],
    [1183, "llsurfup-http", "LL Surfup HTTP"],
    [19315, "keyshadow", "Key Shadow for SASSAFRAS"],
    [19283, "keysrvr", "Key Server for SASSAFRAS"],
    [5963, "indy", "Indy Application Server"],
    [3995, "iss-mgmt-ssl", "ISS Management Svcs SSL"],
    [1124, "hpvmmcontrol", "HP VMM Control"],
    [8500, "fmtp", "Flight Message Transfer Protocol"],
    [1089, "ff-annunc", "FF Annunciation"],
    [10004, "emcrmirccd", "EMC Replication Manager Client"],
    [2251, "dif-port", "Distributed Framework Port"],
    [1087, "cplscrambler-in", "CPL Scrambler Internal"],
    [5280, "xmpp-bosh", "Bidirectional-streams Over Synchronous HTTP (BOSH)"],
    [3871, "avocent-adsap", "Avocent DS Authorization"],
    [3030, "arepa-cas", "Arepa Cas"],
    [
        62078,
        "iphone-sync",
        "Apparently used by iPhone while syncing - "
        "http://code.google.com/p/iphone-elite/source/browse/wiki/Port_62078.wiki",
    ],
    [9091, "xmltec-xmlmail", ""],
    [4111, "xgrid", ""],
    [1334, "writesrv", ""],
    [3261, "winshadow", ""],
    [2522, "windb", ""],
    [5859, "wherehoo", ""],
    [1247, "visionpyramid", ""],
    [9944, "unknown", ""],
    [9943, "unknown", ""],
    [9877, "unknown", ""],
    [9110, "unknown", ""],
    [8654, "unknown", ""],
    [8254, "unknown", ""],
    [8180, "unknown", ""],
    [8011, "unknown", ""],
    [7512, "unknown", ""],
    [7435, "unknown", ""],
    [7103, "unknown", ""],
    [61900, "unknown", ""],
    [61532, "unknown", ""],
    [5922, "unknown", ""],
    [5915, "unknown", ""],
    [5904, "unknown", ""],
    [5822, "unknown", ""],
    [56738, "unknown", ""],
    [55055, "unknown", ""],
    [51493, "unknown", ""],
    [50636, "unknown", ""],
    [50389, "unknown", ""],
    [49175, "unknown", ""],
    [49165, "unknown", ""],
    [49163, "unknown", ""],
    [3546, "unknown", ""],
    [32784, "unknown", ""],
    [27355, "unknown", ""],
    [27353, "unknown", ""],
    [27352, "unknown", ""],
    [24444, "unknown", ""],
    [19780, "unknown", ""],
    [18988, "unknown", ""],
    [16012, "unknown", ""],
    [15742, "unknown", ""],
    [10778, "unknown", ""],
    [4006, "pxc-spvr", ""],
    [2126, "pktcable-cops", ""],
    [4446, "n1-fwp", ""],
    [3880, "igrs", ""],
    [1782, "hp-hcip", ""],
    [1296, "dproxy", ""],
    [9998, "distinct32", ""],
    [
        32777,
        "sometimes-rpc17",
        "filenet-obrok | Sometimes an RPC port on my Solaris box (walld) | "
        "FileNet BPM CORBA",
    ],
    [9040, "tor-trans", "Tor TransPort, www.torproject.org"],
    [32779, "sometimes-rpc21", "Sometimes an RPC port on my Solaris box"],
    [
        1021,
        "exp1",
        "RFC3692-style Experiment 1 (*) [RFC4727] | RFC3692-style Experiment 1",
    ],
    [2021, "servexec", "xinuexpansion1"],
    [666, "doom", "mdqs | Id Software Doom | doom Id Software"],
    [32778, "sometimes-rpc19", "Sometimes an RPC port on my Solaris box (rstatd)"],
    [616, "sco-sysmgr", "SCO System Administration Server"],
    [700, "epp", "Extensible Provisioning Protocol"],
    [1524, "ingreslock", "ingres"],
    [1112, "msql", "icp | mini-sql server | Intelligent Communication Protocol"],
    [5802, "vnc-http-2", "Virtual Network Computer HTTP Access, display 2"],
    [4321, "rwhois", "Remote Who Is"],
    [545, "ekshell", "Kerberos encrypted remote shell -kfall | appleqtcsrvr"],
    [49400, "compaqdiag", "Compaq Web-based management"],
    [84, "ctf", "Common Trace Facility"],
    [38292, "landesk-cba", ""],
    [2040, "lam", ""],
    [3006, "deslogind", "ii-admin | Instant Internet Admin"],
    [
        2111,
        "kx",
        "dsatp | X over kerberos | OPNET Dynamic Sampling Agent Transaction Protocol",
    ],
    [32780, "sometimes-rpc23", "Sometimes an RPC port on my Solaris box"],
    [1084, "ansoft-lm-2", "Anasoft License Manager"],
    [1600, "issd", ""],
    [2048, "dls-monitor", ""],
    [2638, "sybase", "sybaseanywhere | Sybase database | Sybase Anywhere"],
    [
        9111,
        "DragonIDSConsole",
        "hexxorecore | Dragon IDS Console | Multiple Purpose, Distributed Message Bus",
    ],
    [6547, "powerchuteplus", "apc-6547 | APC 6547"],
    [6699, "napster", "Napster File (MP3) sharing software"],
    [16080, "osxwebadmin", "Apple OS X WebAdmin"],
    [2106, "ekshell", "mzap | Kerberos (v4) encrypted rshell | MZAP"],
    [667, "disclose", "campaign contribution disclosures - SDR Technologies"],
    [6007, "X11:7", "X Window server"],
    [1533, "virtual-places", "Virtual Places Software"],
    [5560, "isqlplus", "Oracle web enabled SQL interface (version 10g+)"],
    [1443, "ies-lm", "Integrated Engineering Software"],
    [720, "unknown", ""],
    [2034, "scoremgr", ""],
    [555, "dsf", ""],
    [801, "device", ""],
    [3826, "wormux", "warmux | Wormux server | WarMUX game server"],
    [3814, "neto-dcs", "netO DCS"],
    [7676, "imqbrokerd", "iMQ Broker Rendezvous"],
    [3869, "ovsam-mgmt", "hp OVSAM MgmtServer Disco"],
    [1138, "encrypted_admin", "encrypted-admin | encrypted admin requests"],
    [6567, "esp", "eSilo Storage Protocol"],
    [10003, "documentum_s", "documentum-s | EMC-Documentum Content Server Product"],
    [3221, "xnm-clear-text", "XML NM over TCP"],
    [6025, "x11", "X Window System"],
    [2608, "wag-service", "Wag Service"],
    [
        9200,
        "wap-wsp",
        "WAP connectionless session services | WAP connectionless session service",
    ],
    [7025, "vmsvc-2", "Vormetric Service II"],
    [11111, "vce", "Viral Computing Environment (VCE)"],
    [4279, "vrml-multi-use", "VRML Multi User Systems"],
    [3527, "beserver-msg-q", "VERITAS Backup Exec Server"],
    [1151, "unizensus", "Unizensus Login Server"],
    [8300, "tmi", "Transport Management Interface"],
    [6689, "tsa", "Tofino Security Appliance"],
    [
        9878,
        "kca-service",
        "The KX509 Kerberized Certificate Issuance Protocol in Use in 2012",
    ],
    [8200, "trivnet1", "TRIVNET"],
    [10009, "swdtp-sv", "Systemwalker Desktop Patrol"],
    [8800, "sunwebadmin", "Sun Web Server Admin Service"],
    [5730, "unieng", "Steltor's calendar access"],
    [2394, "ms-olap2", "SQL Server Downlevel OLAP Client Support | MS OLAP 2"],
    [2393, "ms-olap1", "SQL Server Downlevel OLAP Client Support | MS OLAP 1"],
    [2725, "msolap-ptp2", "SQL Analysis Server | MSOLAP PTP2"],
    [5061, "sip-tls", "SIP-TLS"],
    [6566, "sane-port", "SANE Control Port"],
    [9081, "cisco-aqos", "Required for Adaptive Quality of Service"],
    [5678, "rrac", "Remote Replication Agent Connection"],
    [3800, "pwgpsi", "Print Services Interface"],
    [4550, "gds-adppiw-db", "Perman I Interbase Server"],
    [5080, "onscreen", "OnScreen Data Collection Service"],
    [1201, "nucleus-sand", "Nucleus Sand Database Server"],
    [3168, "poweronnud", "Now Up-to-Date Public Server"],
    [1862, "mysql-cm-agent", "MySQL Cluster Manager Agent"],
    [1114, "mini-sql", "Mini SQL"],
    [3905, "mupdate", "Mailbox Update (MUPDATE) protocol"],
    [6510, "mcer-port", "MCER Port"],
    [8383, "m2mservices", "M2m Services"],
    [3914, "listcrt-port-2", "ListCREATOR Port 2"],
    [3971, "lanrevserver", "LANrev Server"],
    [3809, "apocd", "Java Desktop System Configuration Agent"],
    [5033, "jtnetd-server", "Janstor Secure Data"],
    [3517, "802-11-iapp", "IEEE 802.11 WLANs WG IAPP"],
    [
        4900,
        "hfcs",
        "HyperFileSQL Client/Server Database Engine | HFSQL Client/Server "
        "Database Engine",
    ],
    [9418, "git", "Git revision control system | git pack transfer service"],
    [2909, "funk-dialout", "Funk Dialout"],
    [3878, "fotogcad", "FotoG CAD interface"],
    [8042, "fs-agent", "FireScope Agent"],
    [1091, "ff-sm", "FF System Management"],
    [1090, "ff-fms", "FF Fieldbus Message Specification"],
    [3920, "exasoftport1", "Exasoft IP Port"],
    [3945, "emcads", "EMCADS Server Port"],
    [1175, "dossier", "Dossier Server"],
    [3390, "dsc", "Distributed Service Coordinator"],
    [3889, "dandv-tester", "D and V Tester Control Port"],
    [1131, "caspssl", "CAC App Service Protocol Encripted"],
    [8292, "blp3", "Bloomberg professional"],
    [1119, "bnetgame", "Battle.net Chat/Game Protocol"],
    [5087, "biotic", "BIOTIC - Binary Internet of Things Interoperable Communication"],
    [7800, "asr", "Apple Software Restore"],
    [4848, "appserv-http", "App Server - Admin HTTP"],
    [16000, "fmsas", "Administration Server Access"],
    [3324, "active-net", "Active Networks"],
    [3322, "active-net", "Active Networks"],
    [1117, "ardus-mtrns", "ARDUS Multicast Transfer"],
    [5221, "3exmp", "3eTI Extensible Management Protocol for OAMP"],
    [4445, "upnotifyp", ""],
    [9917, "unknown", ""],
    [9575, "unknown", ""],
    [9099, "unknown", ""],
    [9003, "unknown", ""],
    [8290, "unknown", ""],
    [8099, "unknown", ""],
    [8093, "unknown", ""],
    [8045, "unknown", ""],
    [7921, "unknown", ""],
    [7920, "unknown", ""],
    [7496, "unknown", ""],
    [6839, "unknown", ""],
    [6792, "unknown", ""],
    [6779, "unknown", ""],
    [6692, "unknown", ""],
    [6565, "unknown", ""],
    [60443, "unknown", ""],
    [5952, "unknown", ""],
    [5950, "unknown", ""],
    [5907, "unknown", ""],
    [5906, "unknown", ""],
    [5862, "unknown", ""],
    [5850, "unknown", ""],
    [5815, "unknown", ""],
    [5811, "unknown", ""],
    [57797, "unknown", ""],
    [56737, "unknown", ""],
    [5544, "unknown", ""],
    [55056, "unknown", ""],
    [5440, "unknown", ""],
    [54328, "unknown", ""],
    [54045, "unknown", ""],
    [52848, "unknown", ""],
    [52673, "unknown", ""],
    [50500, "unknown", ""],
    [50300, "unknown", ""],
    [49176, "unknown", ""],
    [49167, "unknown", ""],
    [49161, "unknown", ""],
    [44501, "unknown", ""],
    [44176, "unknown", ""],
    [41511, "unknown", ""],
    [40911, "unknown", ""],
    [32785, "unknown", ""],
    [32783, "unknown", ""],
    [30951, "unknown", ""],
    [27356, "unknown", ""],
    [26214, "unknown", ""],
    [25735, "unknown", ""],
    [19350, "unknown", ""],
    [18101, "unknown", ""],
    [18040, "unknown", ""],
    [17877, "unknown", ""],
    [16113, "unknown", ""],
    [15004, "unknown", ""],
    [14441, "unknown", ""],
    [12265, "unknown", ""],
    [12174, "unknown", ""],
    [10215, "unknown", ""],
    [10180, "unknown", ""],
    [4567, "tram", ""],
    [6100, "synchronet-db", ""],
    [4004, "pxc-roid", ""],
    [4005, "pxc-pin", ""],
    [8022, "oa-system", ""],
    [9898, "monkeycom", ""],
    [7999, "irdmi2", ""],
    [1271, "excw", ""],
    [1199, "dmidi", ""],
    [3003, "cgms", ""],
    [1122, "availant-mgr", ""],
    [2323, "3d-nfsd", ""],
    [2022, "down", "xinuexpansion2"],
    [4224, "xtell", "Xtell messenging server"],
    [
        617,
        "sco-dtmgr",
        "SCO Desktop Administration Server or Arkeia (www.arkeia.com) backup "
        "software | SCO Desktop Administration Server",
    ],
    [777, "multiling-http", "Multiling HTTP"],
    [417, "onmux", "Meeting maker"],
    [714, "iris-xpcs", "IRIS over XPCS"],
    [6346, "gnutella", "Gnutella file sharing protocol | gnutella-svc"],
    [981, "unknown", ""],
    [722, "unknown", ""],
    [1009, "unknown", ""],
    [4998, "maybe-veritas", ""],
    [70, "gopher", ""],
    [
        1076,
        "sns_credit",
        "dab-sti-c | Shared Network Services (SNS) for Canadian credit card "
        "authorizations | DAB STI-C",
    ],
    [5999, "ncd-conf", "cvsup | NCD configuration telnet port | CVSup"],
    [10082, "amandaidx", "Amanda indexing"],
    [765, "webster", ""],
    [301, "unknown", ""],
    [524, "ncp", ""],
    [668, "mecomm", ""],
    [2041, "interbase", ""],
    [
        259,
        "esro-gen",
        "efficient short remote operations | Efficient Short Remote Operations",
    ],
    [1984, "bigbrother", "bb | Big Brother monitoring server - www.bb4.com | BB"],
    [
        2068,
        "avocentkvm",
        "avauthsrvprtcl | Avocent KVM Server | Avocent AuthSrv Protocol",
    ],
    [6009, "X11:9", "X Window server"],
    [1417, "timbuktu-srv1", "Timbuktu Service 1 Port"],
    [1434, "ms-sql-m", "Microsoft-SQL-Monitor"],
    [
        44443,
        "coldfusion-auth",
        "ColdFusion Advanced Security/Siteminder Authentication Port (by "
        "Allaire/Netegrity)",
    ],
    [7004, "afs3-kaserver", "AFS/Kerberos authentication service"],
    [1007, "unknown", ""],
    [4343, "unicall", ""],
    [416, "silverplatter", ""],
    [2038, "objectmanager", ""],
    [
        4125,
        "rww",
        "opsview-envoy | Microsoft Remote Web Workplace on Small Business "
        "Server | Opsview Envoy",
    ],
    [1461, "ibm_wrless_lan", "ibm-wrless-lan | IBM Wireless LAN"],
    [9103, "jetdirect", "bacula-sd | HP JetDirect card | Bacula Storage Daemon"],
    [6006, "X11:6", "X Window server"],
    [109, "pop2", "PostOffice V.2 | Post Office Protocol - Version 2"],
    [911, "xact-backup", ""],
    [726, "unknown", ""],
    [1010, "surf", ""],
    [2046, "sdfunc", ""],
    [2035, "imsldoc", ""],
    [7201, "dlip", ""],
    [687, "asipregistry", ""],
    [2013, "raid-am", "raid-cd"],
    [481, "dvs", "ph | Ph service"],
    [
        903,
        "iss-console-mgr",
        "ideafarm-panic | ISS Console Manager | self documenting Telnet Panic "
        "Door | self documenting Panic Door: send 0x00 for info",
    ],
    [125, "locus-map", "Locus PC-Interface Net Map Ser"],
    [6669, "irc", "Internet Relay Chat"],
    [6668, "irc", "Internet Relay Chat"],
    [1455, "esl-lm", "ESL License Manager"],
    [683, "corba-iiop", "CORBA IIOP"],
    [1011, "unknown", ""],
    [2043, "isis-bcast", ""],
    [2047, "dls", ""],
    [256, "fw1-secureremote", 'rap | also "rap" | RAP'],
    [31337, "Elite", "Sometimes interesting stuff can be found here"],
    [
        9929,
        "nping-echo",
        "Nping echo server mode - "
        "https://nmap.org/book/nping-man-echo-mode.html - The port frequency "
        "is made up to keep it (barely) in top 1000 TCP",
    ],
    [5998, "ncd-diag", "NCD diagnostic telnet port"],
    [406, "imsp", "Interactive Mail Support Protocol"],
    [
        44442,
        "coldfusion-auth",
        "ColdFusion Advanced Security/Siteminder Authentication Port (by "
        "Allaire/Netegrity)",
    ],
    [783, "spamassassin", "Apache SpamAssassin spamd"],
    [843, "unknown", ""],
    [2042, "isis", ""],
    [2045, "cdfunc", ""],
    [1875, "westell-stats", "westell stats"],
    [1556, "veritas_pbx", "veritas-pbx | VERITAS Private Branch Exchange"],
    [
        5938,
        "teamviewer",
        "teamviewer - "
        "http://www.teamviewer.com/en/help/334-Which-ports-are-used-by-TeamViewer.aspx",
    ],
    [
        8675,
        "msi-cps-rm",
        "msi-cps-rm-disc | Motorola Solutions Customer Programming Software "
        "for Radio Management | Motorola Solutions Customer Programming "
        "Software for Radio Management Discovery",
    ],
    [1277, "miva-mqs", "mqs"],
    [3972, "iconp", "ict-control Protocol"],
    [3968, "ianywhere-dbns", "iAnywhere DBNS"],
    [3870, "ovsam-d-agent", "hp OVSAM HostAgent Disco"],
    [6068, "gsmp", "gsmp-ancp | GSMP/ANCP"],
    [3050, "gds_db", "gds-db"],
    [5151, "esri_sde", "esri-sde | ESRI SDE Instance | ESRI SDE Remote Start"],
    [3792, "sitewatch", "e-Watch Corporation SiteWatch"],
    [8889, "ddi-tcp-2", "ddi-udp-2 | Desktop Data TCP 1 | NewsEDGE server broadcast"],
    [5063, "csrpc", "centrify secure RPC"],
    [1198, "cajo-discovery", "cajo reference discovery"],
    [1192, "caids-sensor", "caids sensors channel"],
    [4040, "yo-main", "Yo.net main service"],
    [1145, "x9-icue", "X9 iCue Show Control"],
    [6060, "x11", "X Window System"],
    [6051, "x11", "X Window System"],
    [3916, "wysdmc", "WysDM Controller"],
    [7272, "watchme-7272", "WatchMe Monitoring 7272"],
    [9443, "tungsten-https", "WSO2 Tungsten HTTPS"],
    [9444, "wso2esb-console", "WSO2 ESB Administration Console HTTPS"],
    [7024, "vmsvc", "Vormetric service"],
    [13724, "vnetd", "Veritas Network Utility"],
    [4252, "vrml-multi-use", "VRML Multi User Systems"],
    [4200, "vrml-multi-use", "VRML Multi User Systems"],
    [1141, "mxomss", "User Message Service"],
    [1233, "univ-appserver", "Universal App Server"],
    [8765, "ultraseek-http", "Ultraseek HTTP"],
    [3963, "thrp", "Teran Hybrid Routing Protocol"],
    [1137, "trim", "TRIM Workgroup Service"],
    [9191, "sun-as-jpda", "Sun AppSvr JPDA"],
    [3808, "sun-as-iiops-ca", "Sun App Svr-IIOPClntAuth"],
    [8686, "sun-as-jmxrmi", "Sun App Server - JMX/RMI"],
    [3981, "starfish", "Starfish System Admin"],
    [9988, "nsesrvr", "Software Essentials Secure HTTP server"],
    [1163, "sddp", "SmartDialer Data Protocol"],
    [4164, "silverpeakcomm", "Silver Peak Communication Protocol"],
    [3820, "scp", "Siemens AuD SCP"],
    [6481, "servicetags", "Service Tags"],
    [3731, "smap", "Service Manager"],
    [40000, "safetynetp", "SafetyNET p"],
    [2710, "sso-service", "SSO Service"],
    [3852, "sse-app-config", "SSE App Configuration"],
    [3849, "spw-dnspreload", "SPACEWAY DNS Preload | SPACEWAY DNS Prelaod"],
    [3853, "sscan", "SONY scanning protocol"],
    [5081, "sdl-ets", "SDL - Ent Trans Server"],
    [8097, "sac", "SAC Port Id"],
    [3944, "sops", "S-Ops Management"],
    [1287, "routematch", "RouteMatch Com"],
    [3863, "asap-tcp", "RSerPool ASAP (TCP)"],
    [4555, "rsip", "RSIP Port"],
    [4430, "rsqlserver", "REAL SQL Server"],
    [7744, "raqmon-pdu", "RAQMON PDU"],
    [1812, "radius", "RADIUS"],
    [7913, "qo-secure", "QuickObjects secure port"],
    [1166, "qsm-remote", "QSM RemoteExec"],
    [1164, "qsm-proxy", "QSM Proxy Service"],
    [1165, "qsm-gui", "QSM GUI Service"],
    [10160, "qb-db-server", "QB Database Server"],
    [8019, "qbdb", "QB DB Dynamic Port"],
    [4658, "playsta2-app", "PlayStation2 App Port"],
    [7878, "owms", "Opswise Message Service"],
    [1259, "opennl-voice", "Open Network Library Voice"],
    [1092, "obrpd", "Open Business Reporting Protocol"],
]
